import type { GeneratedFile } from '@/lib/types';
import { analyzeProject, type FileAnalysis } from './analyze';

function moduleNameFromPath(path: string): string {
  const base = path.split('/').pop() || path;
  return base.replace(/\.(py|ts|tsx|js|jsx|mjs|php)$/, '');
}

function toImportPath(path: string): string {
  const withoutExt = path.replace(/\.(ts|tsx|js|jsx|mjs)$/, '');
  return `../${withoutExt}`;
}

function pythonModulePath(path: string): string {
  return path.replace(/\.py$/, '').replace(/\//g, '.');
}

// --- Python (pytest) -------------------------------------------------------

function generatePytest(analysis: FileAnalysis): GeneratedFile | null {
  const { file, symbols } = analysis;
  const functions = symbols.filter((s) => s.kind === 'function');
  const routes = symbols.filter((s) => s.kind === 'route');
  if (functions.length === 0 && routes.length === 0) return null;

  const modulePath = pythonModulePath(file.path);
  const lines: string[] = [
    `"""Auto-generated smoke/unit tests for ${file.path}.`,
    '',
    "Generated by Immaculate AI's free, local test-generator (static analysis",
    'based — no LLM calls). Review and extend these before relying on them;',
    'they check that each function/route exists and runs without crashing on',
    'basic input, not full business-logic correctness.',
    '"""',
    'import pytest',
    `from ${modulePath} import ${functions.map((f) => f.name).join(', ') || '*'}`,
    '',
  ];

  for (const fn of functions) {
    lines.push(
      `def test_${fn.name}_is_callable():`,
      `    """${fn.name} should exist and be callable."""`,
      `    assert callable(${fn.name})`,
      '',
      `def test_${fn.name}_does_not_crash_on_no_args():`,
      `    """Smoke test — replace with real arguments/assertions for ${fn.name}."""`,
      '    try:',
      `        ${fn.name}()`,
      '    except TypeError:',
      '        pytest.skip("Requires arguments — add real test data here.")',
      '',
    );
  }

  if (routes.length > 0) {
    lines.push(
      '# --- API route smoke tests -------------------------------------------------',
      '# Adjust the client fixture below to match your app (Flask/FastAPI/etc.)',
      '',
    );
    for (const r of routes) {
      const safeName = r.name.replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'root';
      lines.push(
        `def test_route_${(r.meta || 'get').toLowerCase()}_${safeName}(client):`,
        `    """${r.meta} ${r.name} should respond without a server error."""`,
        `    response = client.${(r.meta || 'GET').toLowerCase()}("${r.name}")`,
        '    assert response.status_code < 500',
        '',
      );
    }
  }

  return {
    path: `tests/test_${moduleNameFromPath(file.path)}.py`,
    content: lines.join('\n'),
    language: 'python',
  };
}

// --- JavaScript / TypeScript (Vitest) --------------------------------------

function generateVitest(analysis: FileAnalysis): GeneratedFile | null {
  const { file, symbols, lang } = analysis;
  const functions = symbols.filter((s) => s.kind === 'function');
  const routes = symbols.filter((s) => s.kind === 'route');
  const components = symbols.filter((s) => s.kind === 'component');
  if (functions.length === 0 && routes.length === 0 && components.length === 0) return null;

  const importPath = toImportPath(file.path);
  const namedImports = [...functions, ...components].map((s) => s.name);

  const lines: string[] = [
    '/**',
    ` * Auto-generated smoke/unit tests for ${file.path}.`,
    ' *',
    " * Generated by Immaculate AI's free, local test-generator (static",
    ' * analysis based — no LLM calls). Review and extend before relying on',
    ' * these; they check existence/callability, not full business logic.',
    ' */',
    `import { describe, it, expect } from 'vitest';`,
  ];
  if (namedImports.length > 0) {
    lines.push(`import { ${namedImports.join(', ')} } from '${importPath}';`);
  }
  lines.push('');

  for (const fn of functions) {
    lines.push(
      `describe('${fn.name}', () => {`,
      `  it('is defined and callable', () => {`,
      `    expect(typeof ${fn.name}).toBe('function');`,
      '  });',
      '',
      `  it('runs without throwing on a basic call (smoke test)', () => {`,
      '    // TODO: replace with real arguments/assertions.',
      '    expect(() => {',
      `      try { ${fn.name}(); } catch (e) { /* likely needs args — ignore for smoke test */ }`,
      '    }).not.toThrow();',
      '  });',
      '});',
      '',
    );
  }

  for (const c of components) {
    lines.push(
      `describe('<${c.name} />', () => {`,
      `  it('is exported', () => {`,
      `    expect(${c.name}).toBeDefined();`,
      '  });',
      '  // TODO: add @testing-library/react render tests once that package is installed.',
      '});',
      '',
    );
  }

  if (routes.length > 0) {
    lines.push(
      '// --- API route smoke tests --------------------------------------------',
      '// Adjust the `request(app)` setup below to match your server entrypoint.',
      '',
    );
    for (const r of routes) {
      lines.push(
        `describe('${r.meta} ${r.name}', () => {`,
        `  it.todo('responds without a server error — wire up supertest against your app');`,
        '});',
        '',
      );
    }
  }

  const ext = lang === 'typescript' ? 'ts' : 'js';
  return {
    path: `tests/${moduleNameFromPath(file.path)}.test.${ext}`,
    content: lines.join('\n'),
    language: lang,
  };
}

// --- PHP (PHPUnit) ----------------------------------------------------------

function generatePhpUnit(analysis: FileAnalysis): GeneratedFile | null {
  const { file, symbols } = analysis;
  const functions = symbols.filter((s) => s.kind === 'function');
  const classes = symbols.filter((s) => s.kind === 'class');
  const routes = symbols.filter((s) => s.kind === 'route');
  if (functions.length === 0 && classes.length === 0 && routes.length === 0) return null;

  const className = `${moduleNameFromPath(file.path).replace(/[^a-zA-Z0-9]/g, '')}Test`;
  const relativeRequire = `../${file.path}`;

  const lines: string[] = [
    '<?php',
    '',
    '/**',
    ` * Auto-generated smoke/unit tests for ${file.path}.`,
    ' *',
    " * Generated by Immaculate AI's free, local test-generator (static",
    ' * analysis based — no LLM calls). Review and extend before relying on',
    ' * these.',
    ' */',
    '',
    'use PHPUnit\\Framework\\TestCase;',
    '',
    `require_once __DIR__ . '/${relativeRequire}';`,
    '',
    `final class ${className} extends TestCase`,
    '{',
  ];

  for (const fn of functions) {
    lines.push(
      `    public function test${capitalize(fn.name)}Exists(): void`,
      '    {',
      `        $this->assertTrue(function_exists('${fn.name}'));`,
      '    }',
      '',
    );
  }

  for (const cls of classes) {
    lines.push(
      `    public function test${cls.name}ClassExists(): void`,
      '    {',
      `        $this->assertTrue(class_exists('${cls.name}'));`,
      '    }',
      '',
    );
  }

  for (const r of routes) {
    const safeName = r.name.replace(/[^a-zA-Z0-9]+/g, '_');
    lines.push(
      `    // TODO: ${r.meta} ${r.name} — wire up an HTTP test client (e.g. Laravel's`,
      "    // built-in test helpers) to assert this route responds successfully.",
      `    public function test${capitalize(safeName)}RouteTodo(): void`,
      '    {',
      "        $this->markTestIncomplete('Add an HTTP test client call here.');",
      '    }',
      '',
    );
  }

  lines.push('}');

  return {
    path: `tests/${className}.php`,
    content: lines.join('\n'),
    language: 'php',
  };
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export interface TestGenerationSummary {
  files: GeneratedFile[];
  analyzed: number;
  skipped: number;
  symbolCount: number;
}

/**
 * Generate a full test suite for a project's files. Entirely local/free —
 * regex-based static analysis + language templates, no API calls.
 */
export function generateTestSuite(files: GeneratedFile[]): TestGenerationSummary {
  const analyses = analyzeProject(files);
  const generated: GeneratedFile[] = [];
  let symbolCount = 0;

  for (const analysis of analyses) {
    symbolCount += analysis.symbols.length;
    let testFile: GeneratedFile | null = null;
    if (analysis.lang === 'python') testFile = generatePytest(analysis);
    else if (analysis.lang === 'javascript' || analysis.lang === 'typescript') testFile = generateVitest(analysis);
    else if (analysis.lang === 'php') testFile = generatePhpUnit(analysis);
    if (testFile) generated.push(testFile);
  }

  return {
    files: generated,
    analyzed: analyses.length,
    skipped: files.length - analyses.length,
    symbolCount,
  };
}
