// Supabase Edge Function: generate-code
//
// Receives a natural-language prompt from an authenticated, non-banned user
// and returns a complete, production-ready code project generated by an LLM.
// Non-programming requests are rejected. The prompt is enriched with *real*
// research pulled live from a dozen public sources (package registries, code
// hosts, docs, Q&A) so the model grounds its output in currently-existing,
// currently-versioned packages and real prior art instead of hallucinating
// them.
//
// LLM PROVIDER CHAIN:
//   1. Pollinations.ai (https://text.pollinations.ai/openai) — completely
//      free, ANONYMOUS, no API key or signup required. This is the
//      PRIMARY provider so the app works out of the box with zero secrets.
//   2. GitHub repository fallback — if Pollinations fails (e.g. rate
//      limited or down), the function searches GitHub's public, keyless
//      repository-search API for a real open-source project matching the
//      prompt, pulls a handful of its actual source files via the
//      Contents API, and returns those as the "generated" project
//      (clearly labelled as sourced from GitHub rather than freshly
//      generated). This guarantees the endpoint basically never
//      hard-fails with nothing to show the user.
//
// (Previously used the paid Anthropic API, whose credit balance ran out,
// then Groq. Groq was removed entirely on 2026-07-29 at the user's
// request — it required a paid-signup API key they didn't want to
// manage, and had been failing with "Invalid API Key" anyway.)
//
// Optional Edge Function secrets (nothing is REQUIRED anymore):
//   GITHUB_API, GITLAB_API, BITBUCKET_API, STACKOVERFLOW_API — optional,
//     raise rate limits on the research lookups only (NOT used by the
//     GitHub fallback provider, which is always anonymous by design)
//
// TEMP DEBUG: on any internal error, also inserts the real error message
// into a `debug_logs` table (service-role only) so it can be inspected via
// SQL, since the Edge Function log viewer only surfaces the HTTP status,
// not the console.error() text. Remove the debugLog() call + block below
// once everything is confirmed stable.
//
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are injected automatically by
// the Supabase Edge Runtime — no need to set them manually.

import { createClient } from 'npm:@supabase/supabase-js@2';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

const GITHUB_API = Deno.env.get('GITHUB_API') || '';
const GITLAB_API = Deno.env.get('GITLAB_API') || '';
const BITBUCKET_API = Deno.env.get('BITBUCKET_API') || '';
const STACKOVERFLOW_API = Deno.env.get('STACKOVERFLOW_API') || '';

const adminClient = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

async function debugLog(context: string, message: string) {
  try {
    await adminClient.from('debug_logs').insert({ context, message: message.slice(0, 4000) });
  } catch {
    // best-effort only
  }
}

interface GeneratedFile {
  path: string;
  content: string;
  language: string;
}

interface GenerationResult {
  is_code_request: boolean;
  refusal_reason?: string;
  title?: string;
  description?: string;
  category?: string;
  primary_language?: string;
  file_structure?: string;
  files?: GeneratedFile[];
  install_guide?: string;
  tags?: string[];
  performance_analysis?: string;
  seo_analysis?: string;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: CORS_HEADERS });
  }

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return json({ error: 'unauthorized' }, 401);

    const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);
    const jwt = authHeader.replace('Bearer ', '');
    const { data: userData, error: userError } = await supabase.auth.getUser(jwt);
    if (userError || !userData.user) return json({ error: 'unauthorized' }, 401);

    const { data: profile } = await supabase
      .from('profiles')
      .select('is_banned')
      .eq('id', userData.user.id)
      .maybeSingle();
    if (profile?.is_banned) return json({ error: 'banned' }, 403);

    const body = await req.json().catch(() => ({}));
    const prompt: string = (body?.prompt ?? '').toString().trim();
    if (!prompt) return json({ error: 'prompt_required' }, 400);
    if (prompt.length > 2000) return json({ error: 'prompt_too_long' }, 400);

    const { data: flagged } = await supabase.rpc('contains_banned_word', { input: prompt });
    if (flagged) return json({ error: 'moderation_blocked' }, 400);

    const ecosystemContext = await analyzeEcosystem(prompt);
    const result = await callLLM(prompt, ecosystemContext);

    if (!result.is_code_request) {
      return json({ error: 'not_code_request', message: result.refusal_reason || 'Only programming/code requests are supported.' }, 422);
    }

    return json({ result });
  } catch (err) {
    const msg = err instanceof Error ? `${err.message}\n${err.stack ?? ''}` : String(err);
    console.error('generate-code error:', msg);
    await debugLog('handler_catch', msg);
    return json({ error: 'internal_error' }, 500);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
  });
}

// ---------------------------------------------------------------------------
// Real package-ecosystem analysis (npm, PyPI, Maven Central, GitHub, ...)
// ---------------------------------------------------------------------------

async function analyzeEcosystem(prompt: string): Promise<string> {
  const lower = prompt.toLowerCase();
  const packageNotes: string[] = [];
  const contextNotes: string[] = [];

  const npmHit = /\b(node|npm|javascript|react|express|next\.?js|typescript|vue|vite)\b/.test(lower);
  const pyHit = /\b(python|django|flask|fastapi|pip|pandas)\b/.test(lower);
  const javaHit = /\b(java|spring|maven|kotlin)\b/.test(lower);
  const rustHit = /\b(rust|cargo|crate)\b/.test(lower);

  const keyword = extractKeyword(prompt);

  await Promise.all([
    npmHit ? withFallback(searchNpm(keyword), packageNotes) : Promise.resolve(),
    pyHit ? withFallback(searchPyPI(keyword), packageNotes) : Promise.resolve(),
    javaHit ? withFallback(searchMaven(keyword), packageNotes) : Promise.resolve(),
    rustHit ? withFallback(searchCratesIo(keyword), packageNotes) : Promise.resolve(),

    withFallback(searchGitHub(keyword), contextNotes),
    withFallback(searchGitLab(keyword), contextNotes),
    withFallback(searchBitbucket(keyword), contextNotes),

    withFallback(searchStackOverflow(keyword), contextNotes),
    npmHit ? withFallback(searchMdn(keyword), contextNotes) : Promise.resolve(),
    withFallback(searchWikipedia(keyword), contextNotes),
    withFallback(searchArchive(keyword), contextNotes),
    withFallback(searchDuckDuckGo(keyword), contextNotes),
  ]);

  const sections: string[] = [];
  if (packageNotes.length) {
    sections.push(
      `Live package/repository research (use these REAL, currently-published package names and versions where relevant — do not invent packages):\n${packageNotes.join('\n')}`,
    );
  }
  if (contextNotes.length) {
    sections.push(
      `Supplementary real-world research (repos, Q&A, docs — use for grounding conventions and terminology, not as literal package names):\n${contextNotes.join('\n')}`,
    );
  }
  return sections.join('\n\n');
}

async function withFallback(p: Promise<string | null>, notes: string[]) {
  try {
    const r = await p;
    if (r) notes.push(r);
  } catch {
    // Best-effort enrichment only; generation must not fail if a registry is down.
  }
}

function extractKeyword(prompt: string): string {
  return prompt.split(/\s+/).slice(0, 6).join(' ');
}

async function searchNpm(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://registry.npmjs.org/-/v1/search?text=${encodeURIComponent(keyword)}&size=3`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const pkgs = (data.objects || [])
    .map((o: { package: { name: string; version: string } }) => `${o.package.name}@${o.package.version}`)
    .join(', ');
  return pkgs ? `- npm: ${pkgs}` : null;
}

async function searchPyPI(keyword: string): Promise<string | null> {
  const firstWord = keyword.split(/\s+/)[0]?.toLowerCase();
  if (!firstWord) return null;
  const res = await fetchWithTimeout(`https://pypi.org/pypi/${encodeURIComponent(firstWord)}/json`);
  if (!res.ok) return null;
  const data = await res.json();
  const name = data?.info?.name;
  const version = data?.info?.version;
  return name && version ? `- PyPI: ${name}==${version}` : null;
}

async function searchMaven(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://search.maven.org/solrsearch/select?q=${encodeURIComponent(keyword)}&rows=3&wt=json`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const docs = data?.response?.docs || [];
  const pkgs = docs.map((d: { g: string; a: string; latestVersion: string }) => `${d.g}:${d.a}:${d.latestVersion}`).join(', ');
  return pkgs ? `- Maven Central: ${pkgs}` : null;
}

async function searchGitHub(keyword: string): Promise<string | null> {
  const headers: Record<string, string> = { Accept: 'application/vnd.github+json', 'User-Agent': 'immaculate-ai' };
  if (GITHUB_API) headers.Authorization = `Bearer ${GITHUB_API}`;
  const res = await fetchWithTimeout(
    `https://api.github.com/search/repositories?q=${encodeURIComponent(keyword)}&sort=stars&order=desc&per_page=3`,
    { headers },
  );
  if (!res.ok) return null;
  const data = await res.json();
  const repos = (data.items || [])
    .map((r: { full_name: string; stargazers_count: number }) => `${r.full_name} (★${r.stargazers_count})`)
    .join(', ');
  return repos ? `- Popular reference repos: ${repos}` : null;
}

async function searchCratesIo(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(`https://crates.io/api/v1/crates?q=${encodeURIComponent(keyword)}&per_page=3`);
  if (!res.ok) return null;
  const data = await res.json();
  const crates = (data.crates || [])
    .map((c: { name: string; max_version: string }) => `${c.name}@${c.max_version}`)
    .join(', ');
  return crates ? `- crates.io: ${crates}` : null;
}

async function searchGitLab(keyword: string): Promise<string | null> {
  const headers: Record<string, string> = {};
  if (GITLAB_API) headers['PRIVATE-TOKEN'] = GITLAB_API;
  const res = await fetchWithTimeout(
    `https://gitlab.com/api/v4/projects?search=${encodeURIComponent(keyword)}&order_by=star_count&sort=desc&per_page=3`,
    { headers },
  );
  if (!res.ok) return null;
  const data = await res.json();
  const repos = (Array.isArray(data) ? data : [])
    .map((p: { path_with_namespace: string; star_count: number }) => `${p.path_with_namespace} (★${p.star_count})`)
    .join(', ');
  return repos ? `- GitLab reference repos: ${repos}` : null;
}

async function searchBitbucket(keyword: string): Promise<string | null> {
  const headers: Record<string, string> = {};
  if (BITBUCKET_API) headers.Authorization = `Bearer ${BITBUCKET_API}`;
  const res = await fetchWithTimeout(
    `https://api.bitbucket.org/2.0/repositories?q=${encodeURIComponent(`name~"${keyword}"`)}&sort=-updated_on&pagelen=3`,
    { headers },
  );
  if (!res.ok) return null;
  const data = await res.json();
  const repos = (data.values || [])
    .map((r: { full_name?: string; name: string }) => r.full_name ?? r.name)
    .join(', ');
  return repos ? `- Bitbucket reference repos: ${repos}` : null;
}

async function searchStackOverflow(keyword: string): Promise<string | null> {
  let url = `https://api.stackexchange.com/2.3/search/advanced?order=desc&sort=relevance&q=${encodeURIComponent(keyword)}&site=stackoverflow&pagesize=3`;
  if (STACKOVERFLOW_API) url += `&key=${encodeURIComponent(STACKOVERFLOW_API)}`;
  const res = await fetchWithTimeout(url);
  if (!res.ok) return null;
  const data = await res.json();
  const items = (data.items || [])
    .map((it: { title: string; score: number }) => `"${it.title}" (score ${it.score})`)
    .join('; ');
  return items ? `- Stack Overflow, related discussions: ${items}` : null;
}

async function searchMdn(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(`https://developer.mozilla.org/api/v1/search?q=${encodeURIComponent(keyword)}&locale=en-US`);
  if (!res.ok) return null;
  const data = await res.json();
  const docs = (data.documents || [])
    .slice(0, 3)
    .map((d: { title: string }) => d.title)
    .join(', ');
  return docs ? `- MDN Web Docs, relevant APIs: ${docs}` : null;
}

async function searchWikipedia(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(keyword)}&format=json&srlimit=2&origin=*`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const hits = (data?.query?.search || [])
    .map((r: { title: string; snippet: string }) => `${r.title} — ${r.snippet.replace(/<[^>]+>/g, '')}`)
    .join(' | ');
  return hits ? `- Wikipedia background: ${hits}` : null;
}

async function searchArchive(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://archive.org/advancedsearch.php?q=${encodeURIComponent(keyword)}&fl[]=identifier&fl[]=title&rows=2&page=1&output=json`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const docs = (data?.response?.docs || [])
    .map((d: { title: string; identifier: string }) => d.title || d.identifier)
    .join(', ');
  return docs ? `- Archive.org, related items: ${docs}` : null;
}

async function searchDuckDuckGo(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://api.duckduckgo.com/?q=${encodeURIComponent(keyword)}&format=json&no_html=1&skip_disambig=1`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  if (data?.AbstractText) return `- DuckDuckGo summary: ${data.AbstractText}`.slice(0, 300);
  return null;
}

async function fetchWithTimeout(url: string, init: RequestInit = {}, timeoutMs = 4000): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

// ---------------------------------------------------------------------------
// LLM call (Groq — free tier, OpenAI-compatible /chat/completions API)
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are the code-generation engine embedded inside "Immaculate AI", a code-sharing platform.

STRICT SCOPE: you ONLY fulfill requests to generate programming code, scripts, software projects, or AI/system prompts for developers. If the user's request is not about writing code/software (e.g. it asks for poetry, general advice, chit-chat, illegal content, or anything non-technical), you MUST refuse.

You must respond with ONLY a single valid JSON object — no markdown fences, no prose before or after. Shape:

{
  "is_code_request": boolean,
  "refusal_reason": string,        // only if is_code_request is false; short, in the user's language
  "title": string,                 // only if is_code_request is true
  "description": string,
  "category": string,               // one of: python, javascript, php, web, api, automation, prompt
  "primary_language": string,
  "file_structure": string,         // a plain-text tree view, e.g. "project/\\n  src/\\n    index.js"
  "files": [ { "path": string, "content": string, "language": string } ],
  "install_guide": string,          // newline-separated numbered steps, backticks for commands
  "tags": string[],
  "performance_analysis": string,
  "seo_analysis": string
}

Rules for actual code generation:
- Produce COMPLETE, working, production-ready code. Never truncate, never use "// ... rest of implementation", never leave TODOs for core functionality.
- Use real, currently-published package names and version numbers. If the message includes a "Live package/repository research" section, prefer those exact package names/versions.
- Follow current security best practices (input validation, no hardcoded secrets, parameterized queries, CORS configured correctly, OWASP Top 10 awareness).
- Prefer modern, idiomatic patterns for the requested language/framework.
- Respond in the same human language the user's prompt is written in for all string fields (title, description, install_guide, analyses), but keep code/comments in English unless the user asked otherwise.
- Keep "files" reasonably sized (typically 2-12 files) but complete enough to actually run after following the install guide.
- Output raw JSON only. Do not wrap it in markdown code fences.`;

async function callLLM(prompt: string, ecosystemContext: string): Promise<GenerationResult> {
  const errors: string[] = [];

  try {
    return await callPollinations(prompt, ecosystemContext);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    errors.push(`Pollinations: ${msg}`);
    await debugLog('pollinations_failed', msg);
  }

  // Groq disabled at user's request (2026-07-29) — was consistently
  // failing with an invalid API key and the user does not want to
  // manage a Groq key. Provider chain is now Pollinations -> GitHub only.

  try {
    return await buildFromGitHub(prompt);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    errors.push(`GitHub fallback: ${msg}`);
    await debugLog('github_fallback_failed', msg);
  }

  throw new Error(`All providers failed. ${errors.join(' | ')}`);
}

function parseJsonFromModel(raw: string): GenerationResult {
  const cleaned = (raw || '{}')
    .trim()
    .replace(/^```json\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/```\s*$/, '');
  try {
    return JSON.parse(cleaned);
  } catch {
    throw new Error('Failed to parse model output as JSON: ' + cleaned.slice(0, 500));
  }
}

// ---------------------------------------------------------------------------
// Provider 1: Pollinations.ai — free, anonymous, no API key required.
// OpenAI-compatible /openai endpoint. Anonymous tier is rate-limited to
// roughly one request per 15s, which is fine for a single user action.
// ---------------------------------------------------------------------------
async function callPollinations(prompt: string, ecosystemContext: string): Promise<GenerationResult> {
  const userMessage = ecosystemContext ? `${prompt}\n\n${ecosystemContext}` : prompt;

  const res = await fetchWithTimeout(
    'https://text.pollinations.ai/openai',
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'openai',
        temperature: 0.3,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userMessage },
        ],
      }),
    },
    30000,
  );

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Pollinations API error ${res.status}: ${text.slice(0, 500)}`);
  }

  const data = await res.json();
  const raw: string = data?.choices?.[0]?.message?.content?.trim() || '{}';
  return parseJsonFromModel(raw);
}

// ---------------------------------------------------------------------------
// Provider 2 (last resort): GitHub repository fallback — no API key needed.
// Searches GitHub's public repository-search endpoint for a real project
// matching the prompt, then pulls a handful of its actual source files via
// the keyless Contents API. Used only if both AI providers above fail.
// ---------------------------------------------------------------------------
const CODE_FILE_EXTENSIONS = [
  '.js', '.jsx', '.ts', '.tsx', '.py', '.php', '.java', '.go', '.rb',
  '.rs', '.c', '.cpp', '.cs', '.html', '.htm', '.css', '.scss', '.less',
  '.json', '.md', '.xml', '.svg', '.liquid', '.twig', '.yml', '.yaml',
  '.sh', '.sql', '.kt', '.swift', '.dart', '.vue', '.svelte', '.mjs',
  '.cjs', '.env.example', '.txt', '.ini', '.toml',
];

const EXCLUDED_PATH_SEGMENTS = [
  'node_modules/', 'vendor/', 'dist/', 'build/', '.git/', 'test/', 'tests/',
  '__tests__/', 'coverage/',
  // Third-party bundled/vendor assets: pre-built library code (jQuery
  // plugins, Bootstrap, etc.), not something written for the matched repo.
  // Serving these as "the result" is exactly the reported bug: a vague
  // query matched a random personal repo and its bundled, already-minified
  // vendor script (plus whatever a template author appended to it, e.g.
  // anti-copy alert() traps) got presented as a clean premium script.
  'assets/vendor/', 'vendor/js/', 'vendor/css/', 'libs/', 'lib/vendor/',
  'wp-content/plugins/', 'wp-content/themes/', 'third-party/', 'thirdparty/',
];

// Path-level signal that a file is a pre-built/bundled third-party asset
// rather than source someone actually wrote for this repo.
const JUNK_FILENAME_PATTERN = /(\.min\.(js|css)$|[-.](bundle|pack|packed)\.(js|css)$|jquery(-|\.)|bootstrap(\.min)?\.(js|css)$|\.map$)/i;

// Content-level obfuscation/quality heuristics. Any single strong signal is
// enough to reject a file: real, hand-written "premium" source is
// readable — multi-line, indented, no hex-named variables, no self-
// invoking decoders. Deliberately conservative: false negatives are fine,
// the goal is just keeping obviously-obfuscated junk out of results.
function looksObfuscatedOrJunk(path: string, content: string): boolean {
  if (JUNK_FILENAME_PATTERN.test(path)) return true;
  if (!/\.(js|jsx|ts|tsx|mjs|cjs)$/i.test(path)) return false; // rest is JS-specific

  const trimmed = content.trim();
  if (!trimmed) return true;

  const lines = trimmed.split('\n');
  const longestLine = Math.max(...lines.map((l) => l.length));
  const avgLineLength = trimmed.length / lines.length;

  const hasHexIdentifiers = /_0x[0-9a-f]{3,8}/i.test(content);
  const hasEvalOrDecoder = /\beval\s*\(|\bunescape\s*\(|String\.fromCharCode\s*\(\s*[\d,\s]{20,}/i.test(content);
  const isSingleGiantLine = lines.length <= 3 && longestLine > 500;
  const isDenselyMinified = avgLineLength > 300 && lines.length < 30;

  // "Anti-copy" traps some free templates bolt onto an otherwise-generic
  // vendor bundle (hijacking keydown + throwing alert()s) — irrelevant to
  // what the user asked for and not something we should hand back at all.
  const hasAntiCopyTrap =
    /onkeydown[\s\S]{0,80}keyCode[\s\S]{0,120}alert\s*\(/i.test(content);

  return hasHexIdentifiers || hasEvalOrDecoder || isSingleGiantLine || isDenselyMinified || hasAntiCopyTrap;
}

// English filler words to strip from a machine-translated prompt before
// using it as a GitHub search query (translation tends to keep verbs like
// "write"/"create" that add noise but no search signal).
const ENGLISH_STOPWORDS = new Set([
  'the', 'a', 'an', 'for', 'and', 'or', 'to', 'of', 'in', 'on', 'with',
  'write', 'create', 'give', 'code', 'me', 'please', 'generate', 'make',
  'build', 'app', 'application', 'project', 'system', 'complete', 'full',
  'automatic', 'automatically', 'smart', 'want', 'need', 'can', 'you',
]);

// Free, keyless machine translation. Two providers, tried in order:
//   1. Google Translate's public web-frontend endpoint
//      (translate.googleapis.com) — the same unofficial endpoint used by
//      popular libraries like googletrans / google-translate-api-x. No key,
//      no official daily cap (unlike MyMemory's ~5000 chars/day), but
//      unofficial and could be rate-limited by IP under heavy load.
//   2. MyMemory (https://mymemory.translated.net) as a fallback — official
//      free tier, ~5000 chars/day anonymous, 500 bytes/request.
// Both are best-effort: if both fail, callers fall back to the other
// (language-agnostic) query candidates below.
async function translateViaGoogle(text: string): Promise<string | null> {
  try {
    const res = await fetchWithTimeout(
      `https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&q=${encodeURIComponent(text)}`,
      {},
      5000,
    );
    if (!res.ok) return null;
    const data = await res.json();
    // Response shape: [[[ "translated", "original", null, null, ... ], ...], ...]
    const translated = (data?.[0] || [])
      .map((seg: unknown[]) => seg?.[0])
      .filter((s: unknown) => typeof s === 'string')
      .join(' ');
    return translated || null;
  } catch {
    return null;
  }
}

async function translateViaMyMemory(text: string): Promise<string | null> {
  try {
    const truncated = text.slice(0, 400); // stay well under the 500-byte request cap
    const res = await fetchWithTimeout(
      `https://api.mymemory.translated.net/get?q=${encodeURIComponent(truncated)}&langpair=auto|en`,
      {},
      5000,
    );
    if (!res.ok) return null;
    const data = await res.json();
    const translated = data?.responseData?.translatedText;
    if (!translated || typeof translated !== 'string') return null;
    if (/MYMEMORY WARNING|QUERY LENGTH LIMIT/i.test(translated)) return null;
    return translated;
  } catch {
    return null;
  }
}

async function translateToEnglish(text: string): Promise<string | null> {
  const truncated = text.slice(0, 400);
  return (await translateViaGoogle(truncated)) ?? (await translateViaMyMemory(truncated));
}

// A small set of borrowed/technical terms that survive translation and are
// strong signals for what kind of repo to look for, even inside a Turkish
// (or other non-English) sentence. Used as a secondary, language-agnostic
// signal alongside the machine translation above.
const KNOWN_TECH_TERMS = [
  'blogger', 'blogspot', 'wordpress', 'shopify', 'woocommerce', 'seo',
  'telegram', 'discord', 'whatsapp', 'instagram', 'twitter', 'facebook',
  'chatbot', 'bot', 'crm', 'cms', 'ecommerce', 'sitemap', 'rss',
  'python', 'javascript', 'typescript', 'php', 'java', 'react', 'vue',
  'node', 'django', 'flask', 'laravel', 'nextjs', 'api', 'rest',
  'scraper', 'crawler', 'automation', 'extension', 'plugin', 'addon',
  'template', 'dashboard', 'admin', 'panel', 'game', 'oyun',
  'phpbb', 'mybb', 'vbulletin', 'discourse', 'forum', 'icon', 'iconset',
  'svg', 'favicon', 'theme', 'skin', 'widget',
];

// Common Turkish filler/verb words that add noise to a GitHub search query
// and should be stripped before falling back to "first content word".
const TURKISH_STOPWORDS = new Set([
  've', 'veya', 'ile', 'için', 'olan', 'olsun', 'gibi', 'bir', 'bu', 'şu',
  'de', 'da', 'ki', 'ise', 'ver', 'yap', 'yaz', 'oluştur', 'oluştur.',
  'kodu', 'kod', 'sistem', 'tam', 'eksiksiz', 'lütfen', 'bana', 'benim',
  'istiyorum', 'istedim', 'yapar', 'mısın', 'misin', 'otomatik', 'akıllı',
]);

async function buildGithubQueryCandidates(prompt: string): Promise<string[]> {
  const candidates: string[] = [];

  // 1. Real machine translation (highest quality signal — e.g. "Mybb
  //    Türkçe dil paketi" -> "Mybb Turkish language pack").
  const translated = await translateToEnglish(prompt);
  if (translated) {
    const translatedWords = translated
      .toLowerCase()
      .replace(/[.,!?;:()"'`]/g, ' ')
      .split(/\s+/)
      .filter((w) => w.length > 2 && !ENGLISH_STOPWORDS.has(w));
    if (translatedWords.length) {
      candidates.push(translatedWords.slice(0, 4).join(' '));
      candidates.push(translatedWords.slice(0, 2).join(' '));
    }
  }

  // 2. Language-agnostic borrowed/technical terms, in case translation
  //    failed or was rate-limited.
  const words = prompt
    .toLowerCase()
    .replace(/[.,!?;:()"'`]/g, ' ')
    .split(/\s+/)
    .filter(Boolean);

  const techHits = words.filter((w) => KNOWN_TECH_TERMS.includes(w));
  if (techHits.length) {
    candidates.push([...new Set(techHits)].slice(0, 3).join(' '));
  }

  const contentWords = words.filter((w) => !TURKISH_STOPWORDS.has(w) && w.length > 2);
  if (contentWords.length) {
    candidates.push(contentWords.slice(0, 3).join(' '));
    candidates.push(contentWords[0]);
  }

  // 3. Original naive 6-word phrase, in case the prompt is already in English.
  candidates.push(extractKeyword(prompt));

  // 4. Last-resort generic categories so this basically never comes up empty.
  candidates.push('starter template', 'boilerplate');

  return [...new Set(candidates.map((c) => c.trim()).filter(Boolean))];
}

async function buildFromGitHub(prompt: string): Promise<GenerationResult> {
  // Deliberately NOT attaching GITHUB_API here even if the secret is set:
  // this function is the last-resort, keyless fallback, and a stale/invalid
  // GITHUB_API secret must never be able to break it. Anonymous GitHub API
  // requests are rate-limited (60/hour) but that's plenty for a fallback path.
  const headers: Record<string, string> = { Accept: 'application/vnd.github+json', 'User-Agent': 'immaculate-ai' };

  // The raw prompt is often in Turkish (or another non-English language)
  // and a literal 6-word phrase almost never matches any real repo name or
  // description. Instead we try several increasingly-broad query
  // candidates and use the first one that returns results:
  //   1. Known tech/CMS keywords detected in the prompt (language-agnostic,
  //      e.g. "blogger", "seo", "wordpress", "telegram bot" survive
  //      translation because they're proper nouns / borrowed terms).
  //   2. The first content word of the prompt with common Turkish filler
  //      words stripped out.
  //   3. A generic category fallback (e.g. "python automation") so the
  //      function essentially never comes up completely empty.
  const queries = await buildGithubQueryCandidates(prompt);

  type Repo = {
    full_name: string;
    default_branch: string;
    html_url: string;
    description: string | null;
    language: string | null;
    stargazers_count: number;
  };

  const triedRepos = new Set<string>();
  let anyReposFound = false;

  for (const q of queries) {
    const searchRes = await fetchWithTimeout(
      `https://api.github.com/search/repositories?q=${encodeURIComponent(q)}&sort=stars&order=desc&per_page=6`,
      { headers },
      8000,
    );
    if (!searchRes.ok) continue;
    const searchData = await searchRes.json();
    const repos = (searchData.items || []) as Repo[];
    if (!repos.length) continue;
    anyReposFound = true;

    // Try every repo returned by this query before moving on to the next,
    // broader query candidate — a query "hitting" doesn't guarantee any of
    // its repos actually contain usable source files (e.g. binary-only or
    // huge monorepos), so we must keep going instead of giving up early.
    for (const repo of repos) {
      if (triedRepos.has(repo.full_name)) continue;
      triedRepos.add(repo.full_name);

      const result = await tryExtractFilesFromRepo(repo, headers);
      if (result) return result;
    }
  }

  if (!anyReposFound) throw new Error('No matching public GitHub repositories found.');
  throw new Error('Found candidate repositories but could not retrieve usable source files from any of them.');
}

async function tryExtractFilesFromRepo(
  repo: {
    full_name: string;
    default_branch: string;
    html_url: string;
    description: string | null;
    language: string | null;
  },
  headers: Record<string, string>,
): Promise<GenerationResult | null> {
  try {
    const treeRes = await fetchWithTimeout(
      `https://api.github.com/repos/${repo.full_name}/git/trees/${repo.default_branch}?recursive=1`,
      { headers },
      8000,
    );
    if (!treeRes.ok) return null;
    const treeData = await treeRes.json();
    const allPaths: string[] = (treeData.tree || [])
      .filter((n: { type: string; path: string }) => n.type === 'blob')
      .map((n: { path: string }) => n.path);

    const candidatePaths = allPaths
      .filter((p) => CODE_FILE_EXTENSIONS.some((ext) => p.toLowerCase().endsWith(ext)))
      .filter((p) => !EXCLUDED_PATH_SEGMENTS.some((seg) => p.toLowerCase().includes(seg)))
      .filter((p) => !JUNK_FILENAME_PATTERN.test(p))
      // Look at more candidates than we ultimately need, since obfuscated/
      // vendor content gets rejected by content below and we don't want a
      // repo full of junk to silently shrink the result to nothing.
      .slice(0, 30);
    if (!candidatePaths.length) return null;

    const files: GeneratedFile[] = [];
    for (const path of candidatePaths) {
      const rawRes = await fetchWithTimeout(
        `https://raw.githubusercontent.com/${repo.full_name}/${repo.default_branch}/${path}`,
        {},
        8000,
      );
      if (!rawRes.ok) continue;
      const content = await rawRes.text();
      if (content.length > 80000) continue; // skip huge files
      if (looksObfuscatedOrJunk(path, content)) continue; // skip minified/obfuscated/anti-copy junk
      files.push({ path, content, language: languageFromPath(path) });
      if (files.length >= 6) break;
    }
    if (!files.length) return null;

    return {
      is_code_request: true,
      title: repo.full_name,
      description:
        (repo.description || `A real, existing open-source project matching your request.`) +
        ` (Sourced live from the public GitHub repository ${repo.full_name} — both AI providers were temporarily unavailable, so this is real working code from an existing project rather than freshly generated code.)`,
      category: 'web',
      primary_language: repo.language || languageFromPath(files[0].path),
      file_structure: files.map((f) => f.path).join('\n'),
      files,
      install_guide: `1. This project was pulled directly from ${repo.html_url}\n2. Clone or download the full repository: \`git clone https://github.com/${repo.full_name}.git\`\n3. Follow that repository's own README for setup and install instructions, since only a subset of files is shown here.`,
      tags: [repo.language || 'code', 'github', 'fallback'],
      performance_analysis: 'Not analyzed — this is existing third-party code pulled as a fallback, not freshly generated.',
      seo_analysis: 'Not applicable — this is existing third-party code pulled as a fallback, not freshly generated.',
    };
  } catch {
    return null;
  }
}

function languageFromPath(path: string): string {
  const ext = path.toLowerCase().split('.').pop() || '';
  const map: Record<string, string> = {
    js: 'javascript', jsx: 'javascript', ts: 'typescript', tsx: 'typescript',
    py: 'python', php: 'php', java: 'java', go: 'go', rb: 'ruby', rs: 'rust',
    c: 'c', cpp: 'cpp', cs: 'csharp', html: 'html', css: 'css', json: 'json', md: 'markdown',
  };
  return map[ext] || 'plaintext';
}
