// Supabase Edge Function: generate-code
//
// Receives a natural-language prompt from an authenticated, non-banned user
// and returns a complete, production-ready code project generated by an LLM
// (Anthropic Claude). Non-programming requests are rejected. The prompt is
// enriched with *real* research pulled live from a dozen public sources
// (package registries, code hosts, docs, Q&A) so the model grounds its
// output in currently-existing, currently-versioned packages and real prior
// art instead of hallucinating them.
//
// Sources wired into this enrichment step (13 total):
//   npm, PyPI, Maven Central, crates.io   - package/registry metadata
//   GitHub, GitLab, Bitbucket             - popular reference repositories
//   Stack Overflow                        - real-world Q&A / gotchas
//   MDN, Wikipedia                        - background/API documentation
//   Archive.org, DuckDuckGo               - general supplementary context
//
// Deliberately NOT wired in here: Google, Yandex, Gist, CodePen, Laravel
// Docs, Microsoft Learn. Those six have no free JSON search API, so
// search-sources (the Library search box) only returns a deep *link* to
// their own search page for them — never actual fetched content. A bare URL
// dropped into the LLM prompt gives Claude nothing to ground on (Claude
// can't visit it), so including them here would add noise, not signal. They
// remain fully wired into the Library's search box, which is exactly where
// a clickable deep link is useful. If real content grounding from those six
// is wanted instead, that would need a different mechanism (e.g. a proper
// scrape/API), not just piping the same secret in here.
//
// Optional Edge Function secrets (all optional — same project-wide secrets
// used by search-sources; every handler below still works key-less, these
// only raise rate limits):
//   GITHUB_API, GITLAB_API, BITBUCKET_API, STACKOVERFLOW_API
//
// Required secret (set via `supabase secrets set` or the Dashboard):
//   ANTHROPIC_API_KEY
//
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are injected automatically by
// the Supabase Edge Runtime — no need to set them manually.

import { createClient } from 'npm:@supabase/supabase-js@2';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const ANTHROPIC_API_KEY = Deno.env.get('ANTHROPIC_API_KEY');
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

const GITHUB_API = Deno.env.get('GITHUB_API') || '';
const GITLAB_API = Deno.env.get('GITLAB_API') || '';
const BITBUCKET_API = Deno.env.get('BITBUCKET_API') || '';
const STACKOVERFLOW_API = Deno.env.get('STACKOVERFLOW_API') || '';

interface GeneratedFile {
  path: string;
  content: string;
  language: string;
}

interface GenerationResult {
  is_code_request: boolean;
  refusal_reason?: string;
  title?: string;
  description?: string;
  category?: string;
  primary_language?: string;
  file_structure?: string;
  files?: GeneratedFile[];
  install_guide?: string;
  tags?: string[];
  performance_analysis?: string;
  seo_analysis?: string;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: CORS_HEADERS });
  }

  try {
    if (!ANTHROPIC_API_KEY) {
      return json({ error: 'server_misconfigured', message: 'ANTHROPIC_API_KEY is not set for this project.' }, 500);
    }

    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return json({ error: 'unauthorized' }, 401);

    // Verify the caller's JWT and load their profile with the service role
    // client (bypasses RLS so we can reliably read ban/role status).
    const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);
    const jwt = authHeader.replace('Bearer ', '');
    const { data: userData, error: userError } = await supabase.auth.getUser(jwt);
    if (userError || !userData.user) return json({ error: 'unauthorized' }, 401);

    const { data: profile } = await supabase
      .from('profiles')
      .select('is_banned')
      .eq('id', userData.user.id)
      .maybeSingle();
    if (profile?.is_banned) return json({ error: 'banned' }, 403);

    const body = await req.json().catch(() => ({}));
    const prompt: string = (body?.prompt ?? '').toString().trim();
    if (!prompt) return json({ error: 'prompt_required' }, 400);
    if (prompt.length > 2000) return json({ error: 'prompt_too_long' }, 400);

    // Reuse the existing DB-side profanity/ban-word check on the raw prompt.
    const { data: flagged } = await supabase.rpc('contains_banned_word', { input: prompt });
    if (flagged) return json({ error: 'moderation_blocked' }, 400);

    const ecosystemContext = await analyzeEcosystem(prompt);
    const result = await callClaude(prompt, ecosystemContext);

    if (!result.is_code_request) {
      return json({ error: 'not_code_request', message: result.refusal_reason || 'Only programming/code requests are supported.' }, 422);
    }

    return json({ result });
  } catch (err) {
    console.error('generate-code error:', err);
    return json({ error: 'internal_error' }, 500);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
  });
}

// ---------------------------------------------------------------------------
// Real package-ecosystem analysis (npm, PyPI, Maven Central, GitHub)
// ---------------------------------------------------------------------------

async function analyzeEcosystem(prompt: string): Promise<string> {
  const lower = prompt.toLowerCase();
  const packageNotes: string[] = [];
  const contextNotes: string[] = [];

  const npmHit = /\b(node|npm|javascript|react|express|next\.?js|typescript|vue|vite)\b/.test(lower);
  const pyHit = /\b(python|django|flask|fastapi|pip|pandas)\b/.test(lower);
  const javaHit = /\b(java|spring|maven|kotlin)\b/.test(lower);
  const rustHit = /\b(rust|cargo|crate)\b/.test(lower);

  const keyword = extractKeyword(prompt);

  await Promise.all([
    // Package/registry metadata — grounds exact names & versions.
    npmHit ? withFallback(searchNpm(keyword), packageNotes) : Promise.resolve(),
    pyHit ? withFallback(searchPyPI(keyword), packageNotes) : Promise.resolve(),
    javaHit ? withFallback(searchMaven(keyword), packageNotes) : Promise.resolve(),
    rustHit ? withFallback(searchCratesIo(keyword), packageNotes) : Promise.resolve(),

    // Reference repositories — real prior art to model structure/conventions on.
    withFallback(searchGitHub(keyword), contextNotes),
    withFallback(searchGitLab(keyword), contextNotes),
    withFallback(searchBitbucket(keyword), contextNotes),

    // Real-world Q&A and docs — surfaces gotchas/APIs a model might otherwise miss.
    withFallback(searchStackOverflow(keyword), contextNotes),
    npmHit ? withFallback(searchMdn(keyword), contextNotes) : Promise.resolve(),
    withFallback(searchWikipedia(keyword), contextNotes),
    withFallback(searchArchive(keyword), contextNotes),
    withFallback(searchDuckDuckGo(keyword), contextNotes),
  ]);

  const sections: string[] = [];
  if (packageNotes.length) {
    sections.push(
      `Live package/repository research (use these REAL, currently-published package names and versions where relevant — do not invent packages):\n${packageNotes.join('\n')}`,
    );
  }
  if (contextNotes.length) {
    sections.push(
      `Supplementary real-world research (repos, Q&A, docs — use for grounding conventions and terminology, not as literal package names):\n${contextNotes.join('\n')}`,
    );
  }
  return sections.join('\n\n');
}

async function withFallback(p: Promise<string | null>, notes: string[]) {
  try {
    const r = await p;
    if (r) notes.push(r);
  } catch {
    // Best-effort enrichment only; generation must not fail if a registry is down.
  }
}

function extractKeyword(prompt: string): string {
  return prompt.split(/\s+/).slice(0, 6).join(' ');
}

async function searchNpm(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://registry.npmjs.org/-/v1/search?text=${encodeURIComponent(keyword)}&size=3`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const pkgs = (data.objects || [])
    .map((o: { package: { name: string; version: string; description?: string } }) =>
      `${o.package.name}@${o.package.version}`,
    )
    .join(', ');
  return pkgs ? `- npm: ${pkgs}` : null;
}

async function searchPyPI(keyword: string): Promise<string | null> {
  const firstWord = keyword.split(/\s+/)[0]?.toLowerCase();
  if (!firstWord) return null;
  const res = await fetchWithTimeout(`https://pypi.org/pypi/${encodeURIComponent(firstWord)}/json`);
  if (!res.ok) return null;
  const data = await res.json();
  const name = data?.info?.name;
  const version = data?.info?.version;
  return name && version ? `- PyPI: ${name}==${version}` : null;
}

async function searchMaven(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://search.maven.org/solrsearch/select?q=${encodeURIComponent(keyword)}&rows=3&wt=json`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const docs = data?.response?.docs || [];
  const pkgs = docs.map((d: { g: string; a: string; latestVersion: string }) => `${d.g}:${d.a}:${d.latestVersion}`).join(', ');
  return pkgs ? `- Maven Central: ${pkgs}` : null;
}

async function searchGitHub(keyword: string): Promise<string | null> {
  const headers: Record<string, string> = { Accept: 'application/vnd.github+json', 'User-Agent': 'immaculate-ai' };
  if (GITHUB_API) headers.Authorization = `Bearer ${GITHUB_API}`;
  const res = await fetchWithTimeout(
    `https://api.github.com/search/repositories?q=${encodeURIComponent(keyword)}&sort=stars&order=desc&per_page=3`,
    { headers },
  );
  if (!res.ok) return null;
  const data = await res.json();
  const repos = (data.items || [])
    .map((r: { full_name: string; stargazers_count: number }) => `${r.full_name} (★${r.stargazers_count})`)
    .join(', ');
  return repos ? `- Popular reference repos: ${repos}` : null;
}

async function searchCratesIo(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(`https://crates.io/api/v1/crates?q=${encodeURIComponent(keyword)}&per_page=3`);
  if (!res.ok) return null;
  const data = await res.json();
  const crates = (data.crates || [])
    .map((c: { name: string; max_version: string }) => `${c.name}@${c.max_version}`)
    .join(', ');
  return crates ? `- crates.io: ${crates}` : null;
}

async function searchGitLab(keyword: string): Promise<string | null> {
  const headers: Record<string, string> = {};
  if (GITLAB_API) headers['PRIVATE-TOKEN'] = GITLAB_API;
  const res = await fetchWithTimeout(
    `https://gitlab.com/api/v4/projects?search=${encodeURIComponent(keyword)}&order_by=star_count&sort=desc&per_page=3`,
    { headers },
  );
  if (!res.ok) return null;
  const data = await res.json();
  const repos = (Array.isArray(data) ? data : [])
    .map((p: { path_with_namespace: string; star_count: number }) => `${p.path_with_namespace} (★${p.star_count})`)
    .join(', ');
  return repos ? `- GitLab reference repos: ${repos}` : null;
}

async function searchBitbucket(keyword: string): Promise<string | null> {
  const headers: Record<string, string> = {};
  if (BITBUCKET_API) headers.Authorization = `Bearer ${BITBUCKET_API}`;
  const res = await fetchWithTimeout(
    `https://api.bitbucket.org/2.0/repositories?q=${encodeURIComponent(`name~"${keyword}"`)}&sort=-updated_on&pagelen=3`,
    { headers },
  );
  if (!res.ok) return null;
  const data = await res.json();
  const repos = (data.values || [])
    .map((r: { full_name?: string; name: string }) => r.full_name ?? r.name)
    .join(', ');
  return repos ? `- Bitbucket reference repos: ${repos}` : null;
}

async function searchStackOverflow(keyword: string): Promise<string | null> {
  let url = `https://api.stackexchange.com/2.3/search/advanced?order=desc&sort=relevance&q=${encodeURIComponent(keyword)}&site=stackoverflow&pagesize=3`;
  if (STACKOVERFLOW_API) url += `&key=${encodeURIComponent(STACKOVERFLOW_API)}`;
  const res = await fetchWithTimeout(url);
  if (!res.ok) return null;
  const data = await res.json();
  const items = (data.items || [])
    .map((it: { title: string; score: number }) => `"${it.title}" (score ${it.score})`)
    .join('; ');
  return items ? `- Stack Overflow, related discussions: ${items}` : null;
}

async function searchMdn(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(`https://developer.mozilla.org/api/v1/search?q=${encodeURIComponent(keyword)}&locale=en-US`);
  if (!res.ok) return null;
  const data = await res.json();
  const docs = (data.documents || [])
    .slice(0, 3)
    .map((d: { title: string }) => d.title)
    .join(', ');
  return docs ? `- MDN Web Docs, relevant APIs: ${docs}` : null;
}

async function searchWikipedia(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(keyword)}&format=json&srlimit=2&origin=*`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const hits = (data?.query?.search || [])
    .map((r: { title: string; snippet: string }) => `${r.title} — ${r.snippet.replace(/<[^>]+>/g, '')}`)
    .join(' | ');
  return hits ? `- Wikipedia background: ${hits}` : null;
}

async function searchArchive(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://archive.org/advancedsearch.php?q=${encodeURIComponent(keyword)}&fl[]=identifier&fl[]=title&rows=2&page=1&output=json`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const docs = (data?.response?.docs || [])
    .map((d: { title: string; identifier: string }) => d.title || d.identifier)
    .join(', ');
  return docs ? `- Archive.org, related items: ${docs}` : null;
}

async function searchDuckDuckGo(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://api.duckduckgo.com/?q=${encodeURIComponent(keyword)}&format=json&no_html=1&skip_disambig=1`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  if (data?.AbstractText) return `- DuckDuckGo summary: ${data.AbstractText}`.slice(0, 300);
  return null;
}

async function fetchWithTimeout(url: string, init: RequestInit = {}, timeoutMs = 4000): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

// ---------------------------------------------------------------------------
// LLM call (Anthropic Claude)
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are the code-generation engine embedded inside "Immaculate AI", a code-sharing platform.

STRICT SCOPE: you ONLY fulfill requests to generate programming code, scripts, software projects, or AI/system prompts for developers. If the user's request is not about writing code/software (e.g. it asks for poetry, general advice, chit-chat, illegal content, or anything non-technical), you MUST refuse.

You must respond with ONLY a single valid JSON object — no markdown fences, no prose before or after. Shape:

{
  "is_code_request": boolean,
  "refusal_reason": string,        // only if is_code_request is false; short, in the user's language
  "title": string,                 // only if is_code_request is true
  "description": string,
  "category": string,               // one of: python, javascript, php, web, api, automation, prompt
  "primary_language": string,
  "file_structure": string,         // a plain-text tree view, e.g. "project/\\n  src/\\n    index.js"
  "files": [ { "path": string, "content": string, "language": string } ],
  "install_guide": string,          // newline-separated numbered steps, backticks for commands
  "tags": string[],
  "performance_analysis": string,
  "seo_analysis": string
}

Rules for actual code generation:
- Produce COMPLETE, working, production-ready code. Never truncate, never use "// ... rest of implementation", never leave TODOs for core functionality.
- Use real, currently-published package names and version numbers. If the message includes a "Live package/repository research" section, prefer those exact package names/versions.
- Follow current security best practices (input validation, no hardcoded secrets, parameterized queries, CORS configured correctly, OWASP Top 10 awareness).
- Prefer modern, idiomatic patterns for the requested language/framework.
- Respond in the same human language the user's prompt is written in for all string fields (title, description, install_guide, analyses), but keep code/comments in English unless the user asked otherwise.
- Keep "files" reasonably sized (typically 2-12 files) but complete enough to actually run after following the install guide.`;

async function callClaude(prompt: string, ecosystemContext: string): Promise<GenerationResult> {
  const userMessage = ecosystemContext ? `${prompt}\n\n${ecosystemContext}` : prompt;

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY!,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-5',
      max_tokens: 16000,
      // Claude Sonnet 5 runs with adaptive thinking by default when no
      // `thinking` field is sent, and max_tokens is a hard cap on
      // thinking + visible response combined. This endpoint only needs the
      // final JSON (no visible reasoning is shown to the user), so thinking
      // is disabled here to guarantee the full 16000-token budget goes to
      // the actual generated code instead of being silently eaten by an
      // invisible reasoning pass — the exact failure mode that causes
      // large/complex projects (e.g. a multi-file XenForo add-on) to get
      // cut off mid-file.
      thinking: { type: 'disabled' },
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userMessage }],
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Anthropic API error ${res.status}: ${text}`);
  }

  const data = await res.json();
  const textBlock = (data.content || []).find((b: { type: string }) => b.type === 'text');
  const raw = textBlock?.text?.trim() || '{}';
  const cleaned = raw.replace(/^```json\s*/i, '').replace(/```\s*$/, '');

  let parsed: GenerationResult;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    throw new Error('Failed to parse model output as JSON');
  }
  return parsed;
}
