// Supabase Edge Function: generate-code
//
// Receives a natural-language prompt from an authenticated, non-banned user
// and returns a complete, production-ready code project generated by an LLM
// (Anthropic Claude). Non-programming requests are rejected. The prompt is
// enriched with *real* package metadata pulled live from npm, PyPI, Maven
// Central and GitHub so the model grounds its output in currently-existing,
// currently-versioned packages instead of hallucinating them.
//
// Required secret (set via `supabase secrets set` or the Dashboard):
//   ANTHROPIC_API_KEY
//
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are injected automatically by
// the Supabase Edge Runtime — no need to set them manually.

import { createClient } from 'npm:@supabase/supabase-js@2';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const ANTHROPIC_API_KEY = Deno.env.get('ANTHROPIC_API_KEY');
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

interface GeneratedFile {
  path: string;
  content: string;
  language: string;
}

interface GenerationResult {
  is_code_request: boolean;
  refusal_reason?: string;
  title?: string;
  description?: string;
  category?: string;
  primary_language?: string;
  file_structure?: string;
  files?: GeneratedFile[];
  install_guide?: string;
  tags?: string[];
  performance_analysis?: string;
  seo_analysis?: string;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: CORS_HEADERS });
  }

  try {
    if (!ANTHROPIC_API_KEY) {
      return json({ error: 'server_misconfigured', message: 'ANTHROPIC_API_KEY is not set for this project.' }, 500);
    }

    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return json({ error: 'unauthorized' }, 401);

    // Verify the caller's JWT and load their profile with the service role
    // client (bypasses RLS so we can reliably read ban/role status).
    const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);
    const jwt = authHeader.replace('Bearer ', '');
    const { data: userData, error: userError } = await supabase.auth.getUser(jwt);
    if (userError || !userData.user) return json({ error: 'unauthorized' }, 401);

    const { data: profile } = await supabase
      .from('profiles')
      .select('is_banned')
      .eq('id', userData.user.id)
      .maybeSingle();
    if (profile?.is_banned) return json({ error: 'banned' }, 403);

    const body = await req.json().catch(() => ({}));
    const prompt: string = (body?.prompt ?? '').toString().trim();
    if (!prompt) return json({ error: 'prompt_required' }, 400);
    if (prompt.length > 2000) return json({ error: 'prompt_too_long' }, 400);

    // Reuse the existing DB-side profanity/ban-word check on the raw prompt.
    const { data: flagged } = await supabase.rpc('contains_banned_word', { input: prompt });
    if (flagged) return json({ error: 'moderation_blocked' }, 400);

    const ecosystemContext = await analyzeEcosystem(prompt);
    const result = await callClaude(prompt, ecosystemContext);

    if (!result.is_code_request) {
      return json({ error: 'not_code_request', message: result.refusal_reason || 'Only programming/code requests are supported.' }, 422);
    }

    return json({ result });
  } catch (err) {
    console.error('generate-code error:', err);
    return json({ error: 'internal_error' }, 500);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
  });
}

// ---------------------------------------------------------------------------
// Real package-ecosystem analysis (npm, PyPI, Maven Central, GitHub)
// ---------------------------------------------------------------------------

async function analyzeEcosystem(prompt: string): Promise<string> {
  const lower = prompt.toLowerCase();
  const notes: string[] = [];

  const npmHit = /\b(node|npm|javascript|react|express|next\.?js|typescript|vue|vite)\b/.test(lower);
  const pyHit = /\b(python|django|flask|fastapi|pip|pandas)\b/.test(lower);
  const javaHit = /\b(java|spring|maven|kotlin)\b/.test(lower);

  const keyword = extractKeyword(prompt);

  await Promise.all([
    npmHit ? withFallback(searchNpm(keyword), notes) : Promise.resolve(),
    pyHit ? withFallback(searchPyPI(keyword), notes) : Promise.resolve(),
    javaHit ? withFallback(searchMaven(keyword), notes) : Promise.resolve(),
    withFallback(searchGitHub(keyword), notes),
  ]);

  return notes.length
    ? `Live package/repository research (use these REAL, currently-published package names and versions where relevant — do not invent packages):\n${notes.join('\n')}`
    : '';
}

async function withFallback(p: Promise<string | null>, notes: string[]) {
  try {
    const r = await p;
    if (r) notes.push(r);
  } catch {
    // Best-effort enrichment only; generation must not fail if a registry is down.
  }
}

function extractKeyword(prompt: string): string {
  return prompt.split(/\s+/).slice(0, 6).join(' ');
}

async function searchNpm(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://registry.npmjs.org/-/v1/search?text=${encodeURIComponent(keyword)}&size=3`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const pkgs = (data.objects || [])
    .map((o: { package: { name: string; version: string; description?: string } }) =>
      `${o.package.name}@${o.package.version}`,
    )
    .join(', ');
  return pkgs ? `- npm: ${pkgs}` : null;
}

async function searchPyPI(keyword: string): Promise<string | null> {
  const firstWord = keyword.split(/\s+/)[0]?.toLowerCase();
  if (!firstWord) return null;
  const res = await fetchWithTimeout(`https://pypi.org/pypi/${encodeURIComponent(firstWord)}/json`);
  if (!res.ok) return null;
  const data = await res.json();
  const name = data?.info?.name;
  const version = data?.info?.version;
  return name && version ? `- PyPI: ${name}==${version}` : null;
}

async function searchMaven(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://search.maven.org/solrsearch/select?q=${encodeURIComponent(keyword)}&rows=3&wt=json`,
  );
  if (!res.ok) return null;
  const data = await res.json();
  const docs = data?.response?.docs || [];
  const pkgs = docs.map((d: { g: string; a: string; latestVersion: string }) => `${d.g}:${d.a}:${d.latestVersion}`).join(', ');
  return pkgs ? `- Maven Central: ${pkgs}` : null;
}

async function searchGitHub(keyword: string): Promise<string | null> {
  const res = await fetchWithTimeout(
    `https://api.github.com/search/repositories?q=${encodeURIComponent(keyword)}&sort=stars&order=desc&per_page=3`,
    { headers: { Accept: 'application/vnd.github+json', 'User-Agent': 'immaculate-ai' } },
  );
  if (!res.ok) return null;
  const data = await res.json();
  const repos = (data.items || [])
    .map((r: { full_name: string; stargazers_count: number }) => `${r.full_name} (★${r.stargazers_count})`)
    .join(', ');
  return repos ? `- Popular reference repos: ${repos}` : null;
}

async function fetchWithTimeout(url: string, init: RequestInit = {}, timeoutMs = 4000): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

// ---------------------------------------------------------------------------
// LLM call (Anthropic Claude)
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are the code-generation engine embedded inside "Immaculate AI", a code-sharing platform.

STRICT SCOPE: you ONLY fulfill requests to generate programming code, scripts, software projects, or AI/system prompts for developers. If the user's request is not about writing code/software (e.g. it asks for poetry, general advice, chit-chat, illegal content, or anything non-technical), you MUST refuse.

You must respond with ONLY a single valid JSON object — no markdown fences, no prose before or after. Shape:

{
  "is_code_request": boolean,
  "refusal_reason": string,        // only if is_code_request is false; short, in the user's language
  "title": string,                 // only if is_code_request is true
  "description": string,
  "category": string,               // one of: python, javascript, php, web, api, automation, prompt
  "primary_language": string,
  "file_structure": string,         // a plain-text tree view, e.g. "project/\\n  src/\\n    index.js"
  "files": [ { "path": string, "content": string, "language": string } ],
  "install_guide": string,          // newline-separated numbered steps, backticks for commands
  "tags": string[],
  "performance_analysis": string,
  "seo_analysis": string
}

Rules for actual code generation:
- Produce COMPLETE, working, production-ready code. Never truncate, never use "// ... rest of implementation", never leave TODOs for core functionality.
- Use real, currently-published package names and version numbers. If the message includes a "Live package/repository research" section, prefer those exact package names/versions.
- Follow current security best practices (input validation, no hardcoded secrets, parameterized queries, CORS configured correctly, OWASP Top 10 awareness).
- Prefer modern, idiomatic patterns for the requested language/framework.
- Respond in the same human language the user's prompt is written in for all string fields (title, description, install_guide, analyses), but keep code/comments in English unless the user asked otherwise.
- Keep "files" reasonably sized (typically 2-12 files) but complete enough to actually run after following the install guide.`;

async function callClaude(prompt: string, ecosystemContext: string): Promise<GenerationResult> {
  const userMessage = ecosystemContext ? `${prompt}\n\n${ecosystemContext}` : prompt;

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY!,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-5',
      max_tokens: 8000,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userMessage }],
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Anthropic API error ${res.status}: ${text}`);
  }

  const data = await res.json();
  const textBlock = (data.content || []).find((b: { type: string }) => b.type === 'text');
  const raw = textBlock?.text?.trim() || '{}';
  const cleaned = raw.replace(/^```json\s*/i, '').replace(/```\s*$/, '');

  let parsed: GenerationResult;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    throw new Error('Failed to parse model output as JSON');
  }
  return parsed;
}
