/*
# Fix: persist performance/SEO analysis + add soft-ownership token

1. Problem being fixed
- `performance_analysis` and `seo_analysis` were generated by the client
  (see src/lib/generator.ts) but were never part of the `projects` schema,
  so every insert silently dropped them and the UI always fell back to a
  generic placeholder string instead of the real analysis.
- The public "projects" table allowed ANY anon/authenticated caller to
  UPDATE or DELETE ANY row (no ownership check at all), so anyone could
  wipe the shared knowledge pool. Since this app has no user accounts,
  we add a lightweight "owner_token" (a random id the browser generates
  and stores locally) so only the browser that created a project can
  modify or delete it, while keeping read/insert fully public.

2. Changes
- Add `performance_analysis` (text, default '')
- Add `seo_analysis` (text, default '')
- Add `owner_token` (text, nullable) — set by the client on insert
- Replace update/delete policies to require a matching `x-owner-token`
  request header instead of being open to everyone
*/

ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS performance_analysis text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS seo_analysis text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS owner_token text;

CREATE INDEX IF NOT EXISTS projects_owner_token_idx ON projects (owner_token);

DROP POLICY IF EXISTS "public_update_projects" ON projects;
DROP POLICY IF EXISTS "owner_update_projects" ON projects;
CREATE POLICY "owner_update_projects" ON projects FOR UPDATE
  TO anon, authenticated
  USING (
    owner_token IS NOT NULL
    AND owner_token = (current_setting('request.headers', true)::json ->> 'x-owner-token')
  )
  WITH CHECK (
    owner_token IS NOT NULL
    AND owner_token = (current_setting('request.headers', true)::json ->> 'x-owner-token')
  );

DROP POLICY IF EXISTS "public_delete_projects" ON projects;
DROP POLICY IF EXISTS "owner_delete_projects" ON projects;
CREATE POLICY "owner_delete_projects" ON projects FOR DELETE
  TO anon, authenticated
  USING (
    owner_token IS NOT NULL
    AND owner_token = (current_setting('request.headers', true)::json ->> 'x-owner-token')
  );
